export const siteConfig = {
  name: "IndiaCab",
  siteUrl: "https://indiacab.in",
  logoUrl: "https://i.ibb.co/WWVb9rZb/dc6e09b0-646e-45b6-a8e3-c36661e95e41.jpg",
  contactEmail: "IndiaCab@gmail.com",
  phoneNumber: "+917004872749",
  description:
    "IndiaCab - Premium and reliable cab services in Bihar and UP. One-way drops, round trips, airport taxi, and outstation cabs at affordable rates. Book Patna to Siwan, Gorakhpur, Varanasi, Delhi, and 50+ routes.",
  keywords: [
    "cab booking",
    "cab service Patna",
    "cab service Siwan",
    "Patna to Siwan cab",
    "Siwan to Patna taxi",
    "Patna airport taxi",
    "Bihar cab service",
    "one way cab Bihar",
    "outstation cab Patna",
    "Patna to Delhi cab",
    "Patna to Varanasi cab",
    "Patna to Gorakhpur cab",
    "Patna to Lucknow cab",
    "Siwan to Gorakhpur cab",
    "Siwan to Varanasi cab",
    "cheap cab Bihar",
    "IndiaCab",
    "taxi service Bihar",
    "online cab booking Bihar",
    "cab service UP",
  ],
};
